#!/usr/bin/env bash

#
# NOTE: This script is run within the chroot after second stage debootstrap!
#

set -e

if [ "$#" -ne 3 ]; then
	echo "Usage: $0 DIST DIST_URL KERNEL_VERSION"
	exit 1
fi

DIST=$1
DIST_URL=$2
KERNEL_VERSION=$3

echo "Running postinstall script..."

# Set root password
echo "root:odroid" | chpasswd

# Add user odroid
useradd -m odroid

# Set odroid password
echo "odroid:odroid" | chpasswd

# Add odroid to sudo group
adduser odroid sudo
adduser odroid audio
adduser odroid video

# Set the locale
sed -i "s/^#[[:space:]]*en_US\.UTF-8\(.*\)/en_US\.UTF-8\1/g" /etc/locale.gen
locale-gen

# Make dpkg/apt-get noninteractive
export DEBIAN_FRONTEND=noninteractive

# Set timezone
dpkg-reconfigure -f noninteractive tzdata

# Initialize /etc/apt/sources.list
echo "deb $DIST_URL $DIST main contrib non-free" > /etc/apt/sources.list
echo "deb-src $DIST_URL $DIST main contrib non-free" >> /etc/apt/sources.list

# Update apt
apt-get -y update

# Generate the initial ramfs
update-initramfs -c -t -k $KERNEL_VERSION

insserv usbmount-start
insserv framebuffer-start
insserv hostname-init

# Prevent apt-get from starting services
echo "#!/bin/sh
exit 101
" > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

# Install extra packages
if [ -f /packages.txt ]; then
	apt-get -y install $(cat /packages.txt);
fi

# Run custom install scripts
if [ -d /postinst ]; then
	find /postinst -maxdepth 1 -type f -executable -not -name "*~" -exec {} \;
fi

# Run custom install scripts for a specific distribution
if [ -d /postinst/$DIST ]; then
	find /postinst/$DIST -maxdepth 1 -type f -executable -not -name "*~" -exec {} \;
fi

# Re-enable services to start
rm /usr/sbin/policy-rc.d

# Cleanup
apt-get autoclean
apt-get clean
dpkg --clear-avail
